name: 'Tinify Image Action (Fork Version)'
description: 'Compress and resize images with the Tinify API'
author: 'loki-empactlabs'
inputs:
  api_key:
    description: 'Tinify API key'
    required: true
  github_token:
    description: 'Repository GITHUB_TOKEN or personal access token secret'
    required: false
    default: ${{ github.token }}
  commit_user_name:
    description: 'Git user.name'
    required: false
    default: ${{ github.actor }}
  commit_user_email:
    description: 'Git user.email'
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
runs:
  using: 'docker'
  image: 'docker://loki2empactlabs/github-action-tinify:latest'
branding:
  icon: 'image'
  color: 'green'
